layout_spectrum: 0.08002145
typography_spectrum: 0.4237379
color:
  saturation: 0.649323
  lightness: 0.004240212
  brandStrength: 0.804233
  rhythmicContrast: 0.938062
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: malotki
